---
- name: Collect running-config and save to file
  hosts: routers
  gather_facts: no
  vars:
    student_id: "{{ lookup('env','ANSIBLE_STUDENT_ID') }}"
    router_name: "{{ lookup('env','ANSIBLE_ROUTER_NAME') | default('CSR1KV') }}"
    out_file: "show_run_{{ student_id }}_{{ router_name }}.txt"
  tasks:
    - name: Get running-config
      ios_command:
        commands:
          - show running-config
      register: showrun

    - name: Save to local file
      copy:
        content: "{{ showrun.stdout[0] }}"
        dest: "{{ out_file }}"
      delegate_to: localhost
